### ISSUE TITLE
Keep checking for new videos

### ISSUE THREAD

**Issue by vincentcox** [dsoprea/youtube-autodownloader#3]
Do I add the script to a cronjob or what do you recommend?

Also another question: where do I edit the youtube-dl commands, for example to save it to audio only?

Thanks for the tool, is exactly what I was looking for.

**Comment by dsoprea** [comment]
Yep. I'll have to add that functionality. If you'd like to, instead, feel free to submit a PR.

**Comment by dsoprea** [comment]
We integrate the API directly. We don't call the command-line. If you'd like to request specific support/features, please open one or more specific issues for them.

**Comment by vincentcox** [comment]
By the way, I think if you run a cronjob [each day](https://crontab.guru/#50_23_*_*_*) you can just use youtube-dl straight away:
`50 23 * * * youtube-dl --dateafter now-1day --extract-audio -o "/home/user/playlistwatcher/%(title)s-%(id)s.%(ext)s" https://www.youtube.com/playlist?list=XXXXXXX`
